#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${CHAPPIE_INSTALL_E2E_IMAGE:-${CHAPPIEDBOT_INSTALL_E2E_IMAGE:-chappie-install-e2e:local}}"
INSTALL_URL="${CHAPPIE_INSTALL_URL:-${CHAPPIEDBOT_INSTALL_URL:-https://chappie.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
CHAPPIE_E2E_MODELS="${CHAPPIE_E2E_MODELS:-${CHAPPIEDBOT_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e CHAPPIE_INSTALL_URL="$INSTALL_URL" \
  -e CHAPPIE_INSTALL_TAG="${CHAPPIE_INSTALL_TAG:-${CHAPPIEDBOT_INSTALL_TAG:-latest}}" \
  -e CHAPPIE_E2E_MODELS="$CHAPPIE_E2E_MODELS" \
  -e CHAPPIE_INSTALL_E2E_PREVIOUS="${CHAPPIE_INSTALL_E2E_PREVIOUS:-${CHAPPIEDBOT_INSTALL_E2E_PREVIOUS:-}}" \
  -e CHAPPIE_INSTALL_E2E_SKIP_PREVIOUS="${CHAPPIE_INSTALL_E2E_SKIP_PREVIOUS:-${CHAPPIEDBOT_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
