apiVersion: v1
kind: Service
metadata:
  name: chappie
  labels:
    app: chappie
spec:
  type: ClusterIP
  selector:
    app: chappie
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      protocol: TCP
