export const browserCoreExamples = [
  "chappie browser status",
  "chappie browser start",
  "chappie browser stop",
  "chappie browser tabs",
  "chappie browser open https://example.com",
  "chappie browser focus abcd1234",
  "chappie browser close abcd1234",
  "chappie browser screenshot",
  "chappie browser screenshot --full-page",
  "chappie browser screenshot --ref 12",
  "chappie browser snapshot",
  "chappie browser snapshot --format aria --limit 200",
  "chappie browser snapshot --efficient",
  "chappie browser snapshot --labels",
];

export const browserActionExamples = [
  "chappie browser navigate https://example.com",
  "chappie browser resize 1280 720",
  "chappie browser click 12 --double",
  'chappie browser type 23 "hello" --submit',
  "chappie browser press Enter",
  "chappie browser hover 44",
  "chappie browser drag 10 11",
  "chappie browser select 9 OptionA OptionB",
  "chappie browser upload /tmp/chappie/uploads/file.pdf",
  'chappie browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "chappie browser dialog --accept",
  'chappie browser wait --text "Done"',
  "chappie browser evaluate --fn '(el) => el.textContent' --ref 7",
  "chappie browser console --level error",
  "chappie browser pdf",
];
